##=====load eureka registry center=====##
eureka:
  client:
    # registry path
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

##========server port=======##
server:
  port: 8762

##=====application name=====##
spring:
  application:
    name: abeille-basic

  ##=====active profile=====##
  profiles:
    active: prod