##=====log common=====##
logging:
  level:
    # control root logger's level for WARN
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    ##=====consul=====##
    consul:
      host: 127.0.0.1
      port: 8500

  ##=====mongodb config=====##
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #      authentication-database: abeille
      #      username: abeille
      #      password: Abeille-top001
      database: abeille


