##========server port=======##
server:
  port: 8763

##=====application name=====##
spring:
  application:
    name: abeille-basic-hypervisor

  ##=====active assets=====##
  profiles:
    active: prod

  ##=====consul config=====##
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true