##========server port=======##
server:
  port: 8762

##=====application name=====##
spring:
  application:
    name: abeille-basic-hypervisor

  ##=====active assets=====##
  profiles:
    active: prod