##=====logger common=====##
logging:
  level:
    # control root logger's level for WARN
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

  ##=====datasource common=====##
  datasource:
    # datasource driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # datasource connection path
    url: jdbc:mysql://127.0.0.1:3306/abeille_basic_assets?useSSL=false&serverTimezone=UTC
    # datasource username
    username: abeille
    # datasource password
    password: abeille.top@123

  ##=====Jpa common=====##
  jpa:
    # datasource dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    # datasource driver
    database: mysql
    # what hibernate will do when application run
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  # server jpa run thread common, hibernate will run with another thread
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  ##=====redis server=====##
  redis:
    # Redis database index(default is 0)
    database: 0
    # Redis server host
    host: 127.0.0.1
    # Redis server port
    port: 7369
    # Redis server password(default is non)
    password: abeille.top@123
    # shutdown timeout(ms)
    lettuce:
      shutdown-timeout: 0ms
