##========server port=======##
server:
  port: 8763
  ssl:
    key-store: classpath:ssl/abeille-top-jwt.jks
    key-alias: abeille-top-jwt
    key-password: abeille-top

##=====application name=====##
spring:
  application:
    name: hypervisor

  ##=====active assets=====##
  profiles:
    active: dev

  ##=====consul config=====##
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true