##=====logger config=====##
logging:
  level:
    # control root logger's level for WARN
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 192.168.31.100
      port: 8500

  ##=====datasource config=====##
  datasource:
    master:
      # datasource driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      # datasource connection path
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/abeille_basic_assets?useSSL=false&serverTimezone=UTC
      # datasource username
      username: root
      # datasource password
      password: root
    slaver:
      # datasource driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      # datasource connection path
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/abeille_basic_assets?useSSL=false&serverTimezone=UTC
      # datasource username
      username: root
      # datasource password
      password: root

  ##=====Jpa config=====##
  jpa:
    # datasource dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    # datasource driver
    database: mysql
    # whether show execute sql
    show-sql: true
    # what hibernate will do when application run
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  # server jpa run thread config, hibernate will run with another thread
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

    ##=====mongodb config=====##
    mongodb:
      host: 192.168.31.100
      port: 27917
      database: abeille
      username: abeille
      password: abeille.top
      authentication-database: abeille