##=====log common=====##
logging:
  level:
    # control root logger's level for INFO
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 122.152.218.103
      port: 8500

  data:
    mongodb:
      host: 122.152.218.103
      port: 27017
      username: abeille
      password: zx110119@@
      database: abeille
      authentication-database: admin