##=====logger common=====##
logging:
  level:
    # control root logger's level for WARN
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

  ##=====datasource common=====##
  datasource:
    master:
      # datasource driver
      driver-class-name: org.mariadb.jdbc.Driver
      # datasource connection path
      jdbcUrl: jdbc:mariadb://127.0.0.1:3036/abeille_basic_assets?useSsl=false&useUnicode=true&characterEncoding=utf-8
      # datasource username
      username: abeille
      # datasource password
      password: abeille.top@123
    slaver:
      # datasource driver
      driver-class-name: org.mariadb.jdbc.Driver
      # datasource connection path
      jdbcUrl: jdbc:mariadb://127.0.0.1:3036/abeille_basic_assets?useSsl=false&useUnicode=true&characterEncoding=utf-8
      # datasource username
      username: abeille
      # datasource password
      password: abeille.top@123

  ##=====Jpa config=====##
  jpa:
    # datasource dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    # datasource driver
    database: mysql
    # whether show execute sql
    show-sql: true
    # what hibernate will do when application run
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  # server jpa run thread common, hibernate will run with another thread
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

    ##=====mongodb config=====##
    mongodb:
      host: 192.168.31.100
      port: 27917
      database: abeille
      username: abeille
      password: abeille.top
      authentication-database: abeille