##=====log common=====##
logging:
  level:
    # control root logger's level for WARN
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 192.168.31.100
      port: 8500

  data:
    mongodb:
      host: 192.168.31.100
      port: 27917
      authentication-database: abeille
      username: abeille
      password: abeille.top
      database: abeille
  #      uri: mongodb://abeille:abeille.top@192.168.31.100:27917/abeille

  ##=====redis server=====##
  redis:
    # Redis database index(default is 0)
    database: 0
    # Redis server host
    host: 192.168.31.100
    # Redis server port
    port: 7369
    # Redis server password(default is non)
    password: abeille.top@123
    # shutdown timeout(ms)
    lettuce:
      shutdown-timeout: 0ms
