##=====log common=====##
logging:
  level:
    # control root logger's level for INFO
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO
      # control org.hibernate logger's level for ERROR
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 122.152.218.103
      port: 8500

  data:
    mongodb:
      host: 122.152.218.103
      port: 27017
      username: abeille
      password: abeille.top@123
      database: abeille
      authentication-database: admin

  ##=====redis server=====##
  redis:
    # Redis database index(default is 0)
    database: 0
    # Redis server host
    host: 122.152.218.103
    # Redis server port
    port: 7369
    # Redis server password(default is non)
    password: abeille.top@123
    # shutdown timeout(ms)
    lettuce:
      shutdown-timeout: 0ms