##========server port=======##
server:
  port: 8764

##=====application name=====##
spring:
  application:
    name: abeille-basic-assets

  ##=====active=====##
  profiles:
    active: dev

  ##=====consul config=====##
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true