##========server port=======##
server:
  port: 8762

##=====application name=====##
spring:
  application:
    name: abeille-basic-authority

  ##=====active profile=====##
  profiles:
    active: prod