##========server port=======##
server:
  port: 8763

##=====application name=====##
spring:
  application:
    name: abeille-basic-payment

  ##=====active payment=====##
  profiles:
    active: dev

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus